export const Constants = {
    LOGIN_LOADING: "LOGIN_LOADING",
    LOGIN: "LOGIN",
    LOGIN_ERROR: "LOGIN_ERROR",

    REGISTER_LOADING: "REGISTER_LOADING",
    REGISTER: "REGISTER",
    REGISTER_ERROR: "REGISTER_ERROR",

    GET_ALL_USERS_LOADING: "GET_ALL_USERS_LOADING",
    GET_ALL_USERS: "GET_ALL_USERS",
    GET_ALL_USERS_ERROR: "GET_ALL_USERS_ERROR",
}